dez_dbt:
  outputs:
    dev:
      dataset: de_zoomcamp_2023_project_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/mrsvllmr/.gc/sa-key-file.json
      location: europe-west1
      method: service-account
      priority: interactive
      project: bright-aloe-381618
      threads: 1
      type: bigquery
  target: dev