# Docker compose: Tool for defining and running multi-container Docker applications
# used to run images as containers
# uses the docker-compose up command
version: '3.7'

  build:
    context: .
    dockerfile: ./Dockerfile

services:
  # install/run Terraform within Docker Compose
  terraform:
    # use a Terraform image; used the version shown used in the video; there might be a newer
    image: hashicorp/terraform:0.12.21 
    # map folders of host machine to folder in Docker container --> called "mounting" (ensures that data will still be available in the container, even after a restart)
    volumes:
      - .:/infra
      # mount configuration read-only
      - ./.config/gcloud:/gcp/config:ro
    working_dir: /infra
    # set environment variables (in this case for authentication)
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/config/application_default_credentials.json \
      # variable allows you to store your gcloud configuration in a non-standard location
      - CLOUDSDK_CONFIG=/gcp/config
